spring:
  resources:
    add-mappings: true

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates/thymeleaf
    suffix: .html

  datasource:
    username: sbsst
    password: sbs123414
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbs_plus

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        user_sql_comments: true
        format_sql: true
        show_sql: true

  output:
    ansi:
      enabled: always

server:
  port: 8011
  mail:
    host: smtp.gmail.com
    port: 587
    username: veryveryhappy17
    password: tasdtmeieuipnreq
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  devtools:
    livereload:
      enabled: true
  freemarker:
    :ache: false
